name: C++ Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kód klónozása
      uses: actions/checkout@v3

    - name: Fordító telepítése
      run: sudo apt-get install -y g++

    - name: C++ fájl fordítása
      run: g++ -o output hello.cpp

    - name: Futatás (opcionális)
      run: ./output

